data:
  data_dir: /data/root/dir
  train_csv: train.csv
  valid_csv: valid.csv
  test_csv: test.csv
  # col names of the image and label files. Pass multiple names as list
  image_cols: [image_1, image_2]
  label_cols: label
  train: True
  valid: True
  test: False
  dataset_type: persistent
  cache_dir: /tmp/monai-cache
  batch_size: 1
debug: false
device: cuda:0
log_dir: logs
loss:
  DiceFocalLoss:
    include_background: true
    softmax: true
    to_onehot_y: true
lr_scheduler:
  OneCycleLR:
    max_lr: 0.0001
model:
  act: PRELU
  channels: [16, 32, 64, 128, 256, 512]
  dropout: 0.1
  norm: BATCH
  num_res_units: 3
  out_channels: 2 # bg, label
  strides: [2, 2, 2, 2, 1]
model_dir: models
ndim: 3
optimizer:
  Adam:
    lr: 0.0001
    weight_decay: 0.001
out_dir: output
overwrite: true
run_id: runs/artificial-tumor
seed: 42
training:
  early_stopping_patience: 250
  max_epochs: 1500
transforms:
  spacing: [0.5, 0.5, 0.5]
  CustomPatchedTransform:
    arg1: some_value
    arg2: some_other_value
  RandCropByPosNegLabeld:
    label_key: label
    neg: 2
    num_samples: 6
    pos: 1
    spatial_size: [128, 128, 128]
  mode: [bilinear, nearest]
  orientation: RAS
  prob: 0.1
patch:
  transforms: path/to/patch/transforms.py # to load CustomPatchedTransform from
